# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pdm-project/pdm
    rev: d150b4e9b41f55df173f57582be3ecb35643c92b  # frozen: 2.29.0
    hooks:
      - id: pdm-lock-check
  - repo: https://github.com/asottile/pyupgrade
    rev: 75992aaa40730136014f34227e0135f63fc951b4 # frozen: v3.21.2
    hooks:
      - id: pyupgrade
        args:
          - --py312-plus
  - repo: local
    hooks:
      - id: prettier
        name: Prettier
        language: node
        entry: prettier
        args: [--write, --ignore-unknown]
        types: [file]
        additional_dependencies:
          - prettier@3.2.5
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 1f1e8bf348ff38fc88619a38d3ca4d9c56abea49  # frozen: v0.16.5
    hooks:
      # Run the linter.
      - id: ruff
        args:
          - --fix
          - --show-fixes
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 7ff8d35ae36a7d2b968f2f90b4c723e292e594ee  # frozen: v2.3.1
    hooks:
      - id: mypy
        args: [--strict, --ignore-missing-imports]
        additional_dependencies:
          - prometheus-client>=0.20.0
          - aiohttp>=3.9.3
